spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    # return 的时候代表消息不可达，设置 broker 不自动删除该消息，
    # 而是返回到生产端，让我们进行一些后续的处理
    template:
      mandatory: true

server:
  port: 8082