#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 200
    
#缓存配置
  cache:
    type: redis
    cache-names: redisCache

#日志配置级别Debug
logging:
  level:
    com.ontop.mapper : DEBUG